services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ftx
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - /home/jan/Projects/ftx-listener/data:/market/data
      # copy the sql script to create tables
      - ./sql/drop_create_tables.sql:/docker-entrypoint-initdb.d/drop_create_tables.sql